name: CharLimit
version: ${project.version}
main: net.kunmc.lab.charlimit.CharLimit
api-version: 1.15
authors: [Kamesuta]

permissions:
  charlimit.set:
    default: op
  charlimit.bypass:
    default: false

commands:
  ch:
    permission: charlimit.set